### ISSUE TITLE
学務情報サービスKUSSOの方にも同様の機能が欲しい

### ISSUE THREAD

**Issue by Elise3993** [HitsujiRere/AutoTermSetterForLMS#1]
### 概要

- 学務情報サービスの履修・成績情報/履修時間割表からいつもLMSに飛んでいるので、そっちの方にも同様の機能が欲しいと思った

**Comment by HitsujiRere** [comment]
version 1.0.5として以下のページを自動設定するよう追加しました!
https://eduweb.sta.kanazawa-u.ac.jp/portal/StudentApp/Regist/RegistList.aspx

**Comment by Elise3993** [comment]
迅速な対応ありがとうございます！
